#!/bin/sh

# Redirect output to stderr.
exec 1>&2

# Check if pnpm is available
if ! command -v pnpm &> /dev/null
then
		echo "pnpm could not be found"
		exit 0
fi

# Check if build succeeded
if ! pnpm build
then
		echo "Build failed"
		exit 1
fi

exit 0
